### ISSUE TITLE
Fluent route registration for async methods its possible?

### ISSUE THREAD

**Issue by tatarincev** [dotarj/FluentRouting#1]
```
public class ApiCartController : Controller
{
 [HttpGet]
        public async Task<ActionResult> GetCurrentCart()
{
.....
}
}
```

**Comment by dotarj** [comment]
I've just tested it and it seems to work. If the method is awaitable, you will get this warning:

"Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call."

But an expression lambda cannot be marked using async (see: 'Can I mark any method as “async”?', http://blogs.msdn.com/b/pfxteam/archive/2012/04/12/async-await-faq.aspx). You will be stuck with the warning unless you suppress it with #pragma warning disable/enable 4014 around the route registration.
